coordinates:
  name: swagger-ui-bundle
  provider: pypi
  type: pypi
revisions:
  0.0.2:
    licensed:
      declared: Apache-2.0
  0.0.8:
    licensed:
      declared: Apache-2.0
  0.0.9:
    licensed:
      declared: Apache-2.0
