coordinates:
  name: swagger-ui
  namespace: org.webjars
  provider: mavencentral
  type: maven
revisions:
  2.1.1:
    licensed:
      declared: Apache-2.0
  2.1.2:
    licensed:
      declared: Apache-2.0
  2.1.3:
    licensed:
      declared: Apache-2.0
  2.1.4:
    licensed:
      declared: Apache-2.0
  2.1.5:
    licensed:
      declared: Apache-2.0
  2.2.0:
    licensed:
      declared: Apache-2.0
  2.2.10:
    licensed:
      declared: Apache-2.0
  2.2.10-1:
    licensed:
      declared: Apache-2.0
  2.2.2:
    licensed:
      declared: Apache-2.0
  2.2.5:
    licensed:
      declared: Apache-2.0
  2.2.6:
    licensed:
      declared: Apache-2.0
  2.2.8:
    licensed:
      declared: Apache-2.0
  3.0.10:
    licensed:
      declared: Apache-2.0
  3.0.14:
    licensed:
      declared: Apache-2.0
  3.0.17:
    licensed:
      declared: Apache-2.0
  3.0.18:
    licensed:
      declared: Apache-2.0
  3.0.19:
    licensed:
      declared: Apache-2.0
  3.0.2:
    licensed:
      declared: Apache-2.0
  3.0.20:
    licensed:
      declared: Apache-2.0
  3.0.21:
    licensed:
      declared: Apache-2.0
  3.0.3:
    licensed:
      declared: Apache-2.0
  3.0.4:
    licensed:
      declared: Apache-2.0
  3.0.5:
    licensed:
      declared: Apache-2.0
  3.0.7:
    licensed:
      declared: Apache-2.0
  3.0.8:
    licensed:
      declared: Apache-2.0
  3.1.2:
    licensed:
      declared: Apache-2.0
  3.1.4:
    licensed:
      declared: Apache-2.0
  3.1.5:
    licensed:
      declared: Apache-2.0
  3.1.6:
    licensed:
      declared: Apache-2.0
  3.1.7:
    licensed:
      declared: Apache-2.0
  3.10.0:
    licensed:
      declared: Apache-2.0
  3.11.0:
    licensed:
      declared: Apache-2.0
  3.12.0:
    licensed:
      declared: Apache-2.0
  3.12.1:
    licensed:
      declared: Apache-2.0
  3.13.0:
    licensed:
      declared: Apache-2.0
  3.13.1:
    licensed:
      declared: Apache-2.0
  3.13.2:
    licensed:
      declared: Apache-2.0
  3.13.3:
    licensed:
      declared: Apache-2.0
  3.13.4:
    licensed:
      declared: Apache-2.0
  3.13.6:
    licensed:
      declared: Apache-2.0
  3.14.0:
    licensed:
      declared: Apache-2.0
  3.14.2:
    licensed:
      declared: Apache-2.0
  3.17.0:
    licensed:
      declared: Apache-2.0
  3.17.1:
    licensed:
      declared: Apache-2.0
  3.17.2:
    licensed:
      declared: Apache-2.0
  3.17.3:
    licensed:
      declared: Apache-2.0
  3.17.4:
    licensed:
      declared: Apache-2.0
  3.17.6:
    licensed:
      declared: Apache-2.0
  3.18.1:
    licensed:
      declared: Apache-2.0
  3.18.2:
    licensed:
      declared: Apache-2.0
  3.19.0:
    licensed:
      declared: Apache-2.0
  3.19.4:
    licensed:
      declared: Apache-2.0
  3.19.5:
    licensed:
      declared: Apache-2.0
  3.2.0:
    licensed:
      declared: Apache-2.0
  3.2.2:
    licensed:
      declared: Apache-2.0
  3.20.0:
    licensed:
      declared: Apache-2.0
  3.20.1:
    licensed:
      declared: Apache-2.0
  3.20.2:
    licensed:
      declared: Apache-2.0
  3.20.3:
    licensed:
      declared: Apache-2.0
  3.20.5:
    licensed:
      declared: Apache-2.0
  3.20.8:
    licensed:
      declared: Apache-2.0
  3.20.9:
    licensed:
      declared: Apache-2.0
  3.22.0:
    licensed:
      declared: Apache-2.0
  3.22.1:
    licensed:
      declared: Apache-2.0
  3.22.2:
    licensed:
      declared: Apache-2.0
  3.23.0:
    licensed:
      declared: Apache-2.0
  3.23.11:
    licensed:
      declared: Apache-2.0
  3.23.2:
    licensed:
      declared: Apache-2.0
  3.23.4:
    licensed:
      declared: Apache-2.0
  3.23.5:
    licensed:
      declared: Apache-2.0
  3.23.8:
    licensed:
      declared: Apache-2.0
  3.24.0:
    licensed:
      declared: Apache-2.0
  3.24.2:
    licensed:
      declared: Apache-2.0
  3.24.3:
    licensed:
      declared: Apache-2.0
  3.25.0:
    licensed:
      declared: Apache-2.0
  3.25.1:
    licensed:
      declared: Apache-2.0
  3.25.2:
    licensed:
      declared: Apache-2.0
  3.25.3:
    licensed:
      declared: Apache-2.0
  3.25.4:
    licensed:
      declared: Apache-2.0
  3.26.0:
    licensed:
      declared: Apache-2.0
  3.27.0:
    licensed:
      declared: Apache-2.0
  3.28.0:
    licensed:
      declared: Apache-2.0
  3.31.1:
    licensed:
      declared: Apache-2.0
  3.32.5:
    licensed:
      declared: Apache-2.0
  3.34.0:
    licensed:
      declared: Apache-2.0
  3.36.1:
    licensed:
      declared: Apache-2.0
  3.37.2:
    licensed:
      declared: Apache-2.0
  3.38.0:
    licensed:
      declared: Apache-2.0
  3.4.4:
    licensed:
      declared: Apache-2.0
  3.42.0:
    licensed:
      declared: Apache-2.0
  3.45.0:
    licensed:
      declared: Apache-2.0
  3.47.1:
    licensed:
      declared: Apache-2.0
  3.5.0:
    licensed:
      declared: Apache-2.0
  3.6.1:
    licensed:
      declared: Apache-2.0
  3.7.0:
    licensed:
      declared: Apache-2.0
  3.8.0:
    licensed:
      declared: Apache-2.0
  3.9.0:
    licensed:
      declared: Apache-2.0
  3.9.1:
    licensed:
      declared: Apache-2.0
  3.9.2:
    licensed:
      declared: Apache-2.0
  3.9.3:
    licensed:
      declared: Apache-2.0
  4.10.3:
    licensed:
      declared: Apache-2.0
