coordinates:
  name: applicationinsights-angularplugin-js
  namespace: '@microsoft'
  provider: npmjs
  type: npm
revisions:
  2.6.3:
    licensed:
      declared: MIT
  2.6.4:
    licensed:
      declared: MIT
  2.7.0:
    licensed:
      declared: MIT
  2.8.0:
    licensed:
      declared: MIT
