coordinates:
  name: neo4j-configuration
  namespace: org.neo4j
  provider: mavencentral
  type: maven
revisions:
  3.5.0-alpha04:
      licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.4.10:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.4.12:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.4.14:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.4.17:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.4.5:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.4.7:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.5.13:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.5.14:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.5.15:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.5.16:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.5.2:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.4.13:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.5.26:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
  3.5.4:
    licensed:
      declared: GPL-3.0-or-later OR OTHER
