coordinates:
  name: dependabot-pub
  provider: rubygems
  type: gem
revisions:
  0.209.0:
    licensed:
      declared: MIT
  0.215.0:
    licensed:
      declared: OTHER
  0.229.0:
    licensed:
      declared: OTHER
