coordinates:
  name: dependabot-terraform
  provider: rubygems
  type: gem
revisions:
  0.129.5:
    licensed:
      declared: OTHER
  0.158.0:
    licensed:
      declared: NONE
  0.162.0:
    licensed:
      declared: OTHER
  0.162.1:
    licensed:
      declared: OTHER
  0.162.2:
    licensed:
      declared: OTHER
  0.169.8:
    licensed:
      declared: OTHER
