coordinates:
  name: dependabot-bundler
  provider: rubygems
  type: gem
revisions:
  0.129.5:
    licensed:
      declared: OTHER
  0.162.1:
    licensed:
      declared: OTHER
  0.162.2:
    licensed:
      declared: OTHER
