coordinates:
  name: Microsoft.ApplicationInsights.PerfCounterCollector
  provider: nuget
  type: nuget
revisions:
  0.15.0-build00179:
    licensed:
      declared: MIT
  0.16.1-build00418:
    licensed:
      declared: MIT
  0.17.0:
    licensed:
      declared: MIT
  1.0.0:
    licensed:
      declared: MIT
  1.1.0:
    licensed:
      declared: MIT
  1.2.1:
    licensed:
      declared: MIT
  1.2.3:
    licensed:
      declared: MIT
  2.0.0:
    licensed:
      declared: MIT
  2.0.0-beta4:
    licensed:
      declared: MIT
  2.1.0:
    licensed:
      declared: MIT
  2.1.0-beta2:
    licensed:
      declared: MIT
  2.1.0-beta4:
    licensed:
      declared: MIT
  2.2.0:
    licensed:
      declared: MIT
  2.2.0-beta1:
    licensed:
      declared: MIT
  2.3.0:
    licensed:
      declared: MIT
  2.4.0:
    licensed:
      declared: MIT
  2.4.1:
    licensed:
      declared: MIT
  2.5.0:
    licensed:
      declared: MIT
  2.5.1:
    licensed:
      declared: MIT
  2.6.1:
    licensed:
      declared: MIT
  2.6.4:
    licensed:
      declared: MIT
  2.7.1:
    licensed:
      declared: MIT
  2.7.2:
    licensed:
      declared: MIT
  2.8.0:
    licensed:
      declared: MIT
  2.8.1:
    licensed:
      declared: MIT
  2.9.0-beta3:
    licensed:
      declared: MIT
