coordinates:
  name: Microsoft.Owin.Security
  provider: nuget
  type: nuget
revisions:
  4.0.0:
    licensed:
      declared: Apache-2.0
  4.0.1:
    files:
      - attributions:
          - Copyright (c) .NET Foundation and Contributors
        license: Apache-2.0
        path: Microsoft.Owin.Security.nuspec
    licensed:
      declared: Apache-2.0
  4.1.0:
    licensed:
      declared: Apache-2.0
