coordinates:
  name: Microsoft.ApplicationInsights.Agent.Intercept
  provider: nuget
  type: nuget
revisions:
  0.17.0:
    licensed:
      declared: MIT
  1.2.0:
    licensed:
      declared: MIT
  1.2.1:
    licensed:
      declared: MIT
  2.0.1:
    licensed:
      declared: MIT
  2.0.7:
    licensed:
      declared: MIT
  2.4.0:
    licensed:
      declared: MIT
