coordinates:
  name: Microsoft.Extensions.Configuration.AzureAppConfiguration
  provider: nuget
  type: nuget
revisions:
  3.0.0:
    licensed:
      declared: OTHER
  3.0.1:
    licensed:
      declared: MIT
