coordinates:
  name: Microsoft.ApplicationInsights.JavaScript
  provider: nuget
  type: nuget
revisions:
  0.11.0-build09387:
    licensed:
      declared: NONE
  0.15.0-build58334:
    licensed:
      declared: MIT
  0.21.5-build00175:
    licensed:
      declared: MIT
  0.22.19-build00125:
    licensed:
      declared: NOASSERTION
  0.22.9-build00167:
    licensed:
      declared: MIT
  1.0.0-build00159:
    licensed:
      declared: MIT
