coordinates:
  name: Microsoft.ApplicationInsights.DependencyCollector
  provider: nuget
  type: nuget
revisions:
  2.4.1:
    licensed:
      declared: MIT
  2.7.1:
    licensed:
      declared: MIT
  2.7.2:
    licensed:
      declared: MIT
