coordinates:
  name: Microsoft.ApplicationInsights
  provider: nuget
  type: nuget
revisions:
  2.4.0:
    licensed:
      declared: MIT
  2.6.4:
    licensed:
      declared: MIT
  2.7.2:
    licensed:
      declared: MIT
