coordinates:
  name: Microsoft.ApplicationInsights.AspNetCore
  provider: nuget
  type: nuget
revisions:
  2.1.1:
    licensed:
      declared: MIT
  2.3.0:
    licensed:
      declared: MIT
  2.4.0:
    licensed:
      declared: MIT    
  2.4.1:
    licensed:
      declared: MIT
