coordinates:
  name: Microsoft.Extensions.Configuration.Binder
  provider: nuget
  type: nuget
revisions:
  2.0.0:
    licensed:
      declared: Apache-2.0
  2.1.1:
    licensed:
      declared: Apache-2.0
