coordinates:
  name: Microsoft.ApplicationInsights.Web
  provider: nuget
  type: nuget
revisions:
  1.2.1:
    licensed:
      declared: MIT
  1.2.3:
    licensed:
      declared: MIT
  2.0.0:
    licensed:
      declared: MIT
  2.1.0:
    licensed:
      declared: MIT
  2.2.0:
    licensed:
      declared: MIT
  2.3.0:
    licensed:
      declared: MIT
  2.4.0:
    licensed:
      declared: MIT
  2.4.1:
    licensed:
      declared: MIT
  2.5.0:
    licensed:
      declared: MIT
  2.5.1:
    licensed:
      declared: MIT
  2.6.4:
    licensed:
      declared: MIT
  2.7.2:
    licensed:
      declared: MIT
  2.8.1:
    licensed:
      declared: MIT
