coordinates:
  name: NetEscapades.Configuration.Yaml
  provider: nuget
  type: nuget
revisions:
  1.6.0:
    licensed:
      declared: MIT
  2.0.0:
    licensed:
      declared: MIT
  2.0.1:
    licensed:
      declared: MIT
  2.1.0:
    licensed:
      declared: MIT
  2.2.0:
    licensed:
      declared: MIT
