coordinates:
  name: NSwag.SwaggerGeneration.AspNetCore
  provider: nuget
  type: nuget
revisions:
  11.19.2:
    licensed:
      declared: MIT
  12.0.14:
    licensed:
      declared: MIT
  12.0.16:
    licensed:
      declared: MIT
  12.2.5:
    licensed:
      declared: MIT
  12.3.1:
    licensed:
      declared: MIT
