coordinates:
  name: NSwag.SwaggerGeneration
  provider: nuget
  type: nuget
revisions:
  11.17.18:
    licensed:
      declared: MIT
  11.19.2:
    licensed:
      declared: MIT
  11.20.1:
    licensed:
      declared: MIT
  12.0.12:
    licensed:
      declared: MIT
  12.0.14:
    licensed:
      declared: MIT
  12.0.16:
    licensed:
      declared: MIT
  12.1.0:
    licensed:
      declared: MIT
  12.2.5:
    licensed:
      declared: MIT
  12.3.1:
    licensed:
      declared: MIT
