coordinates:
  name: NSwag.SwaggerGeneration.WebApi
  provider: nuget
  type: nuget
revisions:
  11.19.2:
    licensed:
      declared: MIT
  11.20.1:
    licensed:
      declared: MIT
  12.0.12:
    licensed:
      declared: MIT
  12.2.5:
    licensed:
      declared: MIT
  12.3.1:
    licensed:
      declared: MIT
