coordinates:
  name: NuGet.Configuration
  provider: nuget
  type: nuget
revisions:
  3.2.0:
    licensed:
      declared: Apache-2.0
  3.5.0:
    licensed:
      declared: Apache-2.0
  3.5.0-beta-final:
    licensed:
      declared: Apache-2.0
  3.5.0-beta2-1484:
    licensed:
      declared: Apache-2.0
  4.2.0:
    licensed:
      declared: Apache-2.0
  4.8.0:
    licensed:
      declared: Apache-2.0
  4.9.4:
    licensed:
      declared: Apache-2.0
