coordinates:
  name: prometheus-net.DotNetRuntime
  provider: nuget
  type: nuget
revisions:
  3.3.1:
    licensed:
      declared: MIT
  3.4.0:
    licensed:
      declared: MIT
  3.4.1:
    licensed:
      declared: MIT
