coordinates:
  name: Swashbuckle.AspNetCore.SwaggerGen
  provider: nuget
  type: nuget
revisions:
  1.0.0:
    licensed:
      declared: MIT
  2.4.0:
    licensed:
      declared: MIT
  3.0.0:
    licensed:
      declared: MIT
  4.0.1:
    licensed:
      declared: MIT
