coordinates:
  name: System.Management.Automation
  provider: nuget
  type: nuget
revisions:
  6.0.4:
    licensed:
      declared: MIT
  6.1.0:
    licensed:
      declared: MIT
  6.1.2:
    licensed:
      declared: MIT
  6.1.6:
    licensed:
      declared: MIT
  6.1.7601.17515:
    licensed:
      declared: MIT
  6.2.0:
    licensed:
      declared: MIT
  6.2.1:
    licensed:
      declared: MIT
  6.2.3:
    licensed:
      declared: MIT
  6.2.4:
    licensed:
      declared: MIT
  6.2.7:
    licensed:
      declared: MIT
  7.0.0:
    licensed:
      declared: MIT
  7.0.2:
    licensed:
      declared: MIT
  7.0.3:
    licensed:
      declared: MIT
  7.0.6:
    licensed:
      declared: MIT
  7.0.7:
    licensed:
      declared: MIT
  7.0.8:
    licensed:
      declared: MIT
