coordinates:
  name: System.Management.Automation
  provider: nuget
  type: nuget
revisions:
  6.1.2:
    licensed:
      declared: MIT
  6.1.7601.17515:
    licensed:
      declared: MIT
  6.2.0:
    licensed:
      declared: MIT
  6.2.3:
    licensed:
      declared: MIT
  7.0.3:
    licensed:
      declared: MIT
