coordinates:
  name: Unity.Configuration
  provider: nuget
  type: nuget
revisions:
  5.1.0:
    licensed:
      declared: Apache-2.0
  5.11.1:
    licensed:
      declared: Apache-2.0
  5.2.3:
    licensed:
      declared: Apache-2.0
