coordinates:
  name: java-grpc-prometheus
  namespace: me.dinowernli
  provider: mavencentral
  type: maven
revisions:
  0.5.0:
    licensed:
      declared: Apache-2.0
  0.6.0:
    licensed:
      declared: Apache-2.0
