coordinates:
  name: gomodules-extracted
  namespace: github.com%2Fdependabot
  provider: golang
  type: go
revisions:
  v0.0.0-20181020215834-1b2f850478a3:
    licensed:
      declared: BSD-3-Clause
  v1.2.0:
    licensed:
      declared: BSD-3-Clause
